name: Checks

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - run: |
          bun install --frozen-lockfile
          bun --filter schwi build

      - run: |
          bun --filter schwi lint
          bun --filter schwi typecheck
